# Use official Node LTS image
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --omit=dev

# Copy application code
COPY . .

# Expose the port your app uses
EXPOSE 80

# Start the app
CMD ["node", "index.js"]
